lora_rank: 32
adaptiveRank: false
initStrategy: minor
criterionThreshold: 0.8
minRank: 2
maxRank: 64
target_modules: 
  - "query"
  - "key"
  - "value"
  - "dense"
peft:
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  task_type: "SEQ_CLS"